/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import CSharpFrameWorkJava.*;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.nio.ByteBuffer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.xml.bind.DatatypeConverter;

/**
 *
 * @author pc
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */

    boolean modificandoTxt;

    public frmMain() {
        MessageBox.DefaultParentComponent = this;
        initComponents();
        modificandoTxt = false;
        txtOffset.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {

            }

            public void removeUpdate(DocumentEvent e) {

                if (!modificandoTxt) {
                    modificandoTxt = true;
                    //si es valido lo convierto a pointer
                    UpdatePointer();
                    modificandoTxt = false;
                }
            }

            public void insertUpdate(DocumentEvent e) {

                if (!modificandoTxt) {
                    modificandoTxt = true;
                    //si es valido lo convierto a pointer
                    UpdatePointer();
                    modificandoTxt = false;
                }

            }

            void UpdatePointer()  {
              txtPointer.setText(Pointer.GetPointer(txtOffset.getText()));
            }

           
        });
        txtPointer.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {

            }

            public void removeUpdate(DocumentEvent e) {

                if (!modificandoTxt) {
                    modificandoTxt = true;
                    //si es valido lo convierto a offset
                    UpdateOffset();
                    modificandoTxt = false;
                }
            }

            void UpdateOffset() {
               txtOffset.setText(Offset.GetOffset(txtPointer.getText()));
            }

         

            public void insertUpdate(DocumentEvent e) {

                if (!modificandoTxt) {
                    modificandoTxt = true;
                    //si es valido lo convierto a offset
                    UpdateOffset();
                    modificandoTxt = false;
                }
            }

        });
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPointer = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtOffset = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnPegarPointer = new javax.swing.JButton();
        btnPegarOffset = new javax.swing.JButton();
        btnCopiarPointer = new javax.swing.JButton();
        btnCopiarOffset = new javax.swing.JButton();
        btnResetCampos = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Offsets And Pointers");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Pointer");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtPointer.setColumns(20);
        txtPointer.setRows(5);
        txtPointer.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtPointerInputMethodTextChanged(evt);
            }
        });
        jScrollPane2.setViewportView(txtPointer);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtOffset.setColumns(20);
        txtOffset.setRows(5);
        txtOffset.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtOffsetInputMethodTextChanged(evt);
            }
        });
        jScrollPane3.setViewportView(txtOffset);
        txtOffset.getAccessibleContext().setAccessibleName("txtOffset");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Offset");

        btnPegarPointer.setText("Pegar");
        btnPegarPointer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegarPointerActionPerformed(evt);
            }
        });

        btnPegarOffset.setText("Pegar");
        btnPegarOffset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegarOffsetActionPerformed(evt);
            }
        });

        btnCopiarPointer.setLabel("Copiar");
        btnCopiarPointer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarPointerActionPerformed(evt);
            }
        });

        btnCopiarOffset.setLabel("Copiar");
        btnCopiarOffset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarOffsetActionPerformed(evt);
            }
        });

        btnResetCampos.setText("Reset");
        btnResetCampos.setToolTipText("");
        btnResetCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetCampos)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPegarOffset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPegarPointer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCopiarOffset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCopiarPointer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPegarPointer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCopiarPointer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPegarOffset)
                        .addComponent(btnCopiarOffset))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnResetCampos)
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("lblPointer");
        jScrollPane2.getAccessibleContext().setAccessibleName("txtPointer");
        jLabel2.getAccessibleContext().setAccessibleName("lblOffset");
        btnPegarPointer.getAccessibleContext().setAccessibleName("btnPegarPointer");
        btnPegarPointer.getAccessibleContext().setAccessibleDescription("");
        btnPegarOffset.getAccessibleContext().setAccessibleName("btnPegarOffset");
        btnCopiarPointer.getAccessibleContext().setAccessibleName("btnCopiarPointer");
        btnCopiarOffset.getAccessibleContext().setAccessibleName("btnCopiarOffset");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnPegarPointerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegarPointerActionPerformed
        // TODO add your handling code here:
        //btnPegarPointer
        txtPointer.setText(Clip.GetClip());
    }//GEN-LAST:event_btnPegarPointerActionPerformed

    private void btnCopiarPointerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarPointerActionPerformed
        // TODO add your handling code here:
        //btnCopiarPointer
        Clip.SetClip(txtPointer.getText());
    }//GEN-LAST:event_btnCopiarPointerActionPerformed

    private void btnPegarOffsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegarOffsetActionPerformed
        // TODO add your handling code here:
        //btnPegarOffset
        txtOffset.setText(Clip.GetClip());
    }//GEN-LAST:event_btnPegarOffsetActionPerformed

    private void btnCopiarOffsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarOffsetActionPerformed
        // TODO add your handling code here:
        //btnCopiarOffset
        Clip.SetClip(txtOffset.getText());
    }//GEN-LAST:event_btnCopiarOffsetActionPerformed
//el TextBox cambiado cambia al otro al llegar al minimo para se un offset o pointer!! 6 char sin contar espacios 0-F
    //si el offset a convertir es mas grande que 32MB lanzar mensaje que ha superado el maximo de la GBA
    //el pointer puede o no tener el 08 o 09 final (depende solo si lo ponen a mano o auto)//yo lo pongo ellos no estan obligados pero supongo que es 08 el acabado
    private void txtPointerInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtPointerInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_txtPointerInputMethodTextChanged

    private void txtOffsetInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtOffsetInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOffsetInputMethodTextChanged

    private void btnResetCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetCamposActionPerformed
        // TODO add your handling code here:
        txtOffset.setText("");
        txtPointer.setText("");
    }//GEN-LAST:event_btnResetCamposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopiarOffset;
    private javax.swing.JButton btnCopiarPointer;
    private javax.swing.JButton btnPegarOffset;
    private javax.swing.JButton btnPegarPointer;
    private javax.swing.JButton btnResetCampos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea txtOffset;
    private javax.swing.JTextArea txtPointer;
    // End of variables declaration//GEN-END:variables
}
